# joaquin Rosales madlib assignment
print("Welcome user")
print("You are a fat rat")
print("Welcome to my game")
print("I will ask you some silly questions")
questionone = input("Give me a random noun ")
sentence = input("Write any sentence,it doesn't even have to make sense")
questionfour = input("give me a random verb ")
questionfive = input("give me another random noun ")
questionsix = input("Now give me a random place ")
questionseven = input("give me a random verb now ending with ing. ")
print("I was at the " + questionsix + "," + questionseven + " some " + questionfive + " and some " + questionone + ". But then, the " + questionone + " started running away, and I became sad. But then, I saw a " + questionfive + " and I got so overjoyed I " + questionfour + " and I was so happy. And here's another thing...." + sentence + ".")